export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";
export const FETCH_CURRENT_USER_REQUEST = "FETCH_CURRENT_USER_REQUEST";
export const FETCH_CURRENT_USER_SUCCESS = "FETCH_CURRENT_USER_SUCCESS";

export const CRYPTOS_FETCHED = "CRYPTOS_FETCHED";
export const CRYPTOS_CREATED = "CRYPTOS_CREATED";

export const TRANSACTIONS_FETCHED = "TRANSACTIONS_FETCHED";
export const TRANSACTIONS_CREATED = "TRANSACTIONS_CREATED";


