export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";
// export const CONFIRM_TOKEN_REQUEST = "CONFIRM_TOKEN_REQUEST";
// export const CONFIRM_TOKEN_FAILURE = "CONFIRM_TOKEN_FAILURE";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";
export const FETCH_CURRENT_USER_REQUEST = "FETCH_CURRENT_USER_REQUEST";
export const FETCH_CURRENT_USER_SUCCESS = "FETCH_CURRENT_USER_SUCCESS";

export const CRYPTOS_FETCHED = "CRYPTOS_FETCHED";
export const CRYPTOS_CREATED = "CRYPTOS_CREATED";
export const CURRENT_CRYPTO_FETCHED = "CURRENT_CRYPTO_FETCHED";

export const TRANSACTIONS_FETCHED = "TRANSACTIONS_FETCHED";
export const TRANSACTIONS_CREATED = "TRANSACTIONS_CREATED";

export const BALANCE_ADD = "BALANCE_ADD";
export const BALANCE_SUBSTRACT = "BALANCE_SUBSTRACT";


